global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using StanNaDan.Entiteti;
global using NHibernate;
global using System.Diagnostics.CodeAnalysis;